<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <OutputExeName>MemoryPackDumper</OutputExeName>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>

        <SuppressTrimAnalysisWarnings>true</SuppressTrimAnalysisWarnings>
        <NoWarn>$(NoWarn);IL2104;IL3002</NoWarn>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ConsoleAppFramework" Version="5.7.13">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\MemoryPackDumper\MemoryPackDumper.csproj"/>
    </ItemGroup>

    <Import Project="PublishOutput.targets" />

</Project>
